### PR TITLE
chore: Configure release-please

### PR DESCRIPTION
**Pull request by mraerino**
Related to https://github.com/FastFilter/xorfilter/issues/25

[Release-Please](https://github.com/googleapis/release-please) will create a running PR with all commits made since the last release. Once you're ready to cut a new release, just merge the PR.

One small caveat is that commits will only show up in the changelog if they follow semantic commit message guidelines (e.g. start with `fix`/`feat`/`chore`. Release-please uses them to determine what kind of version bump it should do. Very useful is that you can mark breaking changes with a bang, e.g. `fix!: bla` and it will do a major bump.
To make sure the commits follow this, i added an action for linting the PR title (assuming you squash-merge PRs).

Do you want to start with a specific version number? E.g. 0.1.0 or something like that?

### CODE REVIEW

**Comment by lemire** [comment]
Let us try it out.

**Comment by lemire** [comment]
Ok. So I merged it. Now what?

**Comment by lemire** [comment]
I do not think it does what you think it should do.

**Comment by mraerino** [comment]
sorry, this was configured for `main`, but your default branch seems to be `master`. my bad.
will do a follow up

**Pull request merged**
